project:
  type: website
  output-dir: docs

website:
  title: "Keyron Linarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      - text: Data Science Projects 
        menu:
        - mario_kart.qmd
        - curly_hair.qmd
        - project2.qmd
        - project3.qmd
        - wai.qmd

      - text: Coding Projects
        menu: 
          - presentation.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

