project:
  type: website
  output-dir: docs


website:
  title: "Keyron Linarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      - text: Data Science Projects 
        menu:
        - mario_kart.qmd
        - curly_hair.qmd
        - chess.qmd
        - project2.qmd
        - project3.qmd
        - wai.qmd


format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true

editor: visual

