project:
  type: website
  output-dir: docs

website:
  title: "KeyronLinarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: mario_kart.qmd
        text: TidyTuesday1
      - href: curly_hair.qmd
        text: TidyTuesday2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

