project:
  type: website
  output-dir: docs


website:
  title: "Rona Linarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      - text: "Resume"
        href: Rona_resume.pdf
      
      - text: Blog
        menu:
        - mario_kart.qmd
        - curly_hair.qmd
        - chess.qmd
        - project2.qmd
        - project3.qmd
        - wai.qmd
        
      - text: Research
        menu: 
          - text: "Summer 2023"
            href: WUSEF_Poster.pdf
          - text: "Summer 2024"
            href: SURP_Poster.pdf
          - text: "Senior Thesis"
            href: Senior_Thesis-25.pdf

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true

editor: visual

resources:
  - Rona_resume.pdf
  - WUSEF_Poster.pdf
  - Senior_Thesis-25.pdf
  - guitar2.JPG

execute:
  cache: true